### ISSUE TITLE
Issue using DirectionHUD on my server

### ISSUE THREAD

**Issue by Sleepybear** [Oth3r/DirectionHUD#5]
Plugin installed on server, shows up fine but when I added my last death as a destination, the server console got spammed with errors:
```
[DirectionHUD] Plugin DirectionHUD v1.4.0+1.18-1.20.6 generated an exception while executing task 29
java.lang.IllegalArgumentException: data (class org.bukkit.Particle$DustOptions) should be class java.lang.Void
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:71) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2964) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2944) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2924) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.utils.Player.spawnParticleLine(Player.java:204) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
        at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.particles(LoopManager.java:103) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
        at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.tick(LoopManager.java:36) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
        at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.DirectionHUD$1.run(DirectionHUD.java:58) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

I am using Paper as my server software with version 1.20.6.

**Comment by Oth3r** [comment]
try out the [latest version](https://modrinth.com/plugin/directionhud-plugin/versions) (1.4.1), should be fixed there

**Comment by Sleepybear** [comment]
That did seem to fix the problem. Thank you!
