### ISSUE TITLE
Having issues seeing particles on MC Java 1.21 Paper MC.

### ISSUE THREAD

**Issue by HoboBIll** [Oth3r/DirectionHUD#6]
## Info

Server: 
MC Java 1.21 Paper MC

Plugins:
Backpacks
Chunky
DirectionHUD
floodgate
Geyser
GravityControl
SkinRestorer

## Problem

when I set a destination to go to I dont see any particles and get this error in my server console

## Logs

```
[20:47:41 WARN]: [DirectionHUD] Plugin DirectionHUD v1.4.0+1.18-1.20.6 generated an exception while executing task 2
java.lang.IllegalArgumentException: data (class org.bukkit.Particle$DustOptions) should be class java.lang.Void
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:71) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2993) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2983) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2963) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2943) ~[paper-1.21.jar:1.21-36-dd31654]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.utils.Player.spawnParticleLine(Player.java:204) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.particles(LoopManager.java:103) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.tick(LoopManager.java:36) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.DirectionHUD$1.run(DirectionHUD.java:58) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-36-dd31654]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:47:42 WARN]: [DirectionHUD] Plugin DirectionHUD v1.4.0+1.18-1.20.6 generated an exception while executing task 2
java.lang.IllegalArgumentException: data (class org.bukkit.Particle$DustOptions) should be class java.lang.Void
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:71) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2993) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2983) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2963) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2943) ~[paper-1.21.jar:1.21-36-dd31654]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.utils.Player.spawnParticleLine(Player.java:204) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.particles(LoopManager.java:103) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.tick(LoopManager.java:36) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.DirectionHUD$1.run(DirectionHUD.java:58) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-36-dd31654]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:47:43 WARN]: [DirectionHUD] Plugin DirectionHUD v1.4.0+1.18-1.20.6 generated an exception while executing task 2
java.lang.IllegalArgumentException: data (class org.bukkit.Particle$DustOptions) should be class java.lang.Void
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:71) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2993) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2983) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2963) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2943) ~[paper-1.21.jar:1.21-36-dd31654]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.utils.Player.spawnParticleLine(Player.java:204) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.particles(LoopManager.java:103) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.tick(LoopManager.java:36) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.DirectionHUD$1.run(DirectionHUD.java:58) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-36-dd31654]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:47:44 WARN]: [DirectionHUD] Plugin DirectionHUD v1.4.0+1.18-1.20.6 generated an exception while executing task 2
java.lang.IllegalArgumentException: data (class org.bukkit.Particle$DustOptions) should be class java.lang.Void
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:71) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2993) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2983) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2963) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2943) ~[paper-1.21.jar:1.21-36-dd31654]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.utils.Player.spawnParticleLine(Player.java:204) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.particles(LoopManager.java:103) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.common.LoopManager.tick(LoopManager.java:36) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at directionhud-spigot-1.4.0+1.18-1.20.6.jar/one.oth3r.directionhud.DirectionHUD$1.run(DirectionHUD.java:58) ~[directionhud-spigot-1.4.0+1.18-1.20.6.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-36-dd31654]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-36-dd31654]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Oth3r** [comment]
update to [v1.4.1](https://modrinth.com/plugin/directionhud-plugin/version/1.4.1+1.18-1.20.6) and see if that fixes your issue.

**Comment by HoboBIll** [comment]
> update to [v1.4.1](https://modrinth.com/plugin/directionhud-plugin/version/1.4.1+1.18-1.20.6) and see if that fixes your issue.

Just tried it out and it works thanks!
