### ISSUE TITLE
Unconfigured dimensions crash upon entering

### ISSUE THREAD

**Issue by fennecr** [Oth3r/DirectionHUD#7]
I'm using a TARDIS mod, and it creates dynamic dimensions that can't be added to the config. Looks like when directionhud sees that it has no timeSettings it crashes the server.

Time: 2024-09-25 03:10:03
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "one.oth3r.directionhud.common.files.dimension.DimensionEntry$Time.getEnabled()" because "timeSettings" is null
	at one.oth3r.directionhud.common.Hud$build.getTimeModule(Hud.java:322)
	at one.oth3r.directionhud.common.Hud$build.getHUDInstructions(Hud.java:248)
	at one.oth3r.directionhud.common.LoopManager.HUDTickLogic(LoopManager.java:75)
	at one.oth3r.directionhud.common.LoopManager.tick(LoopManager.java:31)
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:108)
	at one.oth3r.directionhud.DirectionHUD.lambda$onInitialize$7(DirectionHUD.java:92)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
	at net.minecraft.server.MinecraftServer.handler$bkm002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7662)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:940)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)

**Comment by Oth3r** [comment]
I see, thanks for the bug report, looking into it!

**Comment by Oth3r** [comment]
fixed with cf9f40801100968ceb5d181294ddc746b93834dc, patch soon to come
